export const Component = {
	Application: Symbol.for('Application'),
	LoggerInterface: Symbol.for('LoggerInterface'),
	ConfigInterface: Symbol.for('ConfigInterface'),
	DatabaseInterface: Symbol.for('DatabaseInterface'),
	UserServiceInterface: Symbol.for('UserServiceInterface'),
	UserModel: Symbol.for('UserModel'),
	FilmServiceInterface: Symbol.for('FilmServiceInterface'),
	FilmModel: Symbol.for('FilmModel'),
	GenreServiceInterface: Symbol.for('GenreServiceInterface'),
	GenreModel: Symbol.for('GenreModel'),
	FilmController: Symbol.for('FilmController'),
	UserController: Symbol.for('UserController'),
	ExceptionFilterInterface: Symbol.for('ExceptionFilterInterface'),
} as const;
